version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
