version: '3'
services:
  db:
    image: postgres:17
    volumes:
      - ./.postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
